### ISSUE TITLE
Decide what caching headers (if any) to send for more “static” resources

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/misc-server#10]
See the discussion at https://github.com/whatwg/misc-server/pull/8#discussion_r136722792

**Comment by annevk** [comment]
It's tempting to ask mnot for advice...

https://jakearchibald.com/2016/caching-best-practices/ has some information too. Just `ETag` seems fine, but I guess the main question is whether we want more than that, to avoid constant revalidation.

**Comment by domenic** [comment]
It's also worth mentioning that we'll be putting a service worker caching layer in front of most things anyway :)

**Comment by foolip** [comment]
I think the only thing to optimize for here is responsiveness for the user, we need not spend too much effort trying to minimize our bandwidth usage, I'm pretty sure that will be OK anyway.

**Comment by annevk** [comment]
Well, revalidation takes time, but with a service worker in front that concern would indeed go away.

**Comment by foolip** [comment]
I'm going to do Cache-Control "public" and an expiry time of 1 week for static resources, matching https://github.com/whatwg/html/blob/master/images/.htaccess. That's also what the config was in some places that I've already transitioned, but I'm worried that moving HTML to new hosting will require taking caching more seriously.

**Comment by foolip** [comment]
No, actually, I'll go with `Cache-Control: max-age=604800`, which is the first pattern in https://jakearchibald.com/2016/caching-best-practices/ and just one line of configuration in nginx.

Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control it looks like the public thing isn't important.
