### ISSUE TITLE
Make html-differences.whatwg.org redirect to https://html.spec.whatwg.org/dev/

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#100]
Once we've done that:

1. Close https://github.com/whatwg/meta/issues/2.
2. Archive https://github.com/whatwg/html-differences.

cc @zcorpan @sideshowbarker

**Comment by zcorpan** [comment]
Sounds good to me. HTML 4 is about one generation ago; this doc has served its purpose.

**Comment by sideshowbarker** [comment]
SGTM2

**Comment by annevk** [comment]
Thanks for rolling this out @sideshowbarker! I took care of the two items in OP.
