### ISSUE TITLE
Put multicol config in source control

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#112]
blog.whatwg.org and wiki.whatwg.org are on this machine, but its setup isn't reproducible.

**Comment by foolip** [comment]
IIRC, @GPHemsley created the initial setup for wiki, and I then added the blog to that. It's MediaWiki + Wordpress running on Apache with a local MySQL server.

**Comment by domenic** [comment]
From https://github.com/whatwg/misc-server/pull/110#issuecomment-561248505

> It isn't tracked anywhere, filed https://github.com/whatwg/misc-server/issues/112. Unfortunately, the only way of having any confidence that a setup would work is by setting it up from scratch. And since it includes a database, that data wouldn't be tracked anywhere except in VM backups.
>
> To reduce the maintenance by a lot, we'd need to use a managed database solution and put the blog+wiki setup in a Dockerfile, or transition both to something that requires only static hosting. But for the latter I have low confidence that any existing tools would convert markup with enough fidelity, so the bulk of the work would be in verifying the transition, not in making it.

The database is certainly a sticking point, but it does seem like we could figure out something similar to the existing setups (no Docker needed, necessarily). Just run a bunch of scripts to install things, and then there's a magic step where you put some database files in a certain location.

I'm mainly concerned about not losing the institutional knowledge of things like the headers that we keep tweaking.

**Comment by foolip** [comment]
I believe all the interesting config is in /etc/apache2/sites-available/ + /etc/apache2/conf-available/zz_local.conf.

**Comment by annevk** [comment]
Note that the WordPress theme we have is at https://github.com/whatwg/blog.whatwg.org though it's currently private. That should probably be part of an eventual set of steps/setup.

**Comment by GPHemsley** [comment]
The majority of the MediaWiki setup comes straight from their git repos, with some customizations of ours in LocalSettings.php.

I have documentation for myself on how to upgrade it. I also may be the only one with the database passwords.

Let me know what you need and where you want to put it.

**Comment by domenic** [comment]
Fixed! https://github.com/whatwg/wiki.whatwg.org

**Comment by GPHemsley** [comment]
@domenic I am miffed that you did all that without my involvement. And in deploying without coordinating with me, you appear to have clobbered the documentation and backups I had stored on the server. I can no longer SSH in. I would presume from this that I am no longer maintaining the wiki, but you've left my e-mail address in plaintext in the configuration file that you've now committed to the repo.

**Comment by domenic** [comment]
@GPHemsley oh no, I am so sorry! I got carried away with the excitement of getting this fully deployed and upgraded and was careless in how my work would impact others.

How can I make this right? I will restore the server from the snapshot we took so you can SSH in as a start. Feel free to reach out by email or Matrix or however for anything else I can do.
