### ISSUE TITLE
Don't send double x-content-type-options on wiki.whatwg.org

### ISSUE THREAD

**Issue by domenic** [whatwg/misc-server#115]
See https://github.com/whatwg/misc-server/blob/70b3fcb40fc395029019700fca852f05b0199362/test/x-headers.js#L15

**Comment by GPHemsley** [comment]
I assume this was here for a reason? Do we know what that reason was?

**Comment by annevk** [comment]
I suspect it's just a bug. Other than testing how clients deal with multiple header values there's no reason for this (and I think this might end up with no policy due to clients rejecting it).

**Comment by GPHemsley** [comment]
Where's the bug? MediaWiki? Or somewhere else?

**Comment by annevk** [comment]
If we set the header for this server and MediaWiki tries to set it as well (by appending instead of overwriting), that might well be the problem.
