### ISSUE TITLE
Remove HotCat and UTCLiveClock gadgets from wiki.whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#119]
They fetch resources from wikimedia.org and mediawiki.org and privacy-policy-wise it's better if we have no third-party domains (third-party domain being any domain that is not part of whatwg.org (or whatpr.org, though that's best avoided generally too)).

**Comment by GPHemsley** [comment]
@annevk Note that as both of these are gadgets, they are able to be turned on and off at the user level (though they are currently enabled for everyone by default) and also that we can choose to edit them locally to not fetch external resources. Would either of these alternative options meet the privacy policy requirements?

**Comment by GPHemsley** [comment]
See:
https://wiki.whatwg.org/wiki/Special:Gadgets
https://wiki.whatwg.org/wiki/MediaWiki:Gadget-HotCat.js
https://wiki.whatwg.org/wiki/MediaWiki:Gadget-UTCLiveClock.js

**Comment by annevk** [comment]
Given that we're mostly migrating content away from the wiki it's not clear to me it's worth the hassle, but yeah, disabling them by default is probably fine (or ensuring no external resources are fetched).

**Comment by GPHemsley** [comment]
Silly me, I could have done this a month ago. It's just a matter of editing a wiki page.

In any case, turned HotCat and UTCLiveClock off by default:
https://wiki.whatwg.org/index.php?title=MediaWiki:Gadgets-definition&oldid=10315

**Comment by GPHemsley** [comment]
For future reference, the revisionjumper, modrollback, and ReferenceTooltips gadgets also should not be enabled by default because they have external references.

**Comment by annevk** [comment]
Thanks Gordon!
