### ISSUE TITLE
review-drafts/ should also be sorted by date

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#138]
What we have for commit-snapshots in https://github.com/whatwg/misc-server/blob/master/debian/marquee/nginx/conf/whatwg.conf should also apply to review-drafts. https://stackoverflow.com/questions/35320674/how-can-i-have-same-rule-for-two-locations-in-nginx-config has some suggestions. I don't have a preference, but happy to supply a PR. (Surprisingly https://nginx.org/en/docs/http/ngx_http_core_module.html#location does not seem to cover this.)

cc @sideshowbarker

**Comment by sideshowbarker** [comment]
I'll make time to look into this (if @foolip doesn't get to it first)

**Comment by foolip** [comment]
Looks like a simple setting, but I won't be at a computer to do real work in a while, so if you can do it, @sideshowbarker, that would be great.

**Comment by sideshowbarker** [comment]
Raised https://github.com/whatwg/misc-server/pull/139

**Comment by annevk** [comment]
I'm not sure #139 worked. https://dom.spec.whatwg.org/review-drafts/ does seem sorted, but https://dom.spec.whatwg.org/commit-snapshots/ is not.

**Comment by sideshowbarker** [comment]
I'll look into it right now

**Comment by sideshowbarker** [comment]
sigh ᠁ my fault, careless oversight. will fix properly

**Comment by sideshowbarker** [comment]
OK, raised https://github.com/whatwg/misc-server/issues/138
