### ISSUE TITLE
https://resources.whatwg.org/biblio.json has the wrong encoding

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#15]
https://resources.whatwg.org/biblio.json says "HÃ¥kon Wium Lie" :(

@sideshowbarker

**Comment by annevk** [comment]
Works fine in Firefox. I suspect Chrome might not always decode JSON resources as UTF-8. See https://github.com/whatwg/html/issues/1403.

**Comment by sideshowbarker** [comment]
I get `Håkon Wium Lie` as expected in all browsers I’ve tried: in desktop Safari and both on desktop and mobile Chrome and Firefox

**Comment by foolip** [comment]
These are the header:
```
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Thu, 28 Sep 2017 22:59:52 GMT
Content-Type: application/json
Content-Length: 3190
Last-Modified: Wed, 27 Sep 2017 08:22:07 GMT
Connection: keep-alive
Vary: Accept-Encoding
ETag: "59cb5faf-c76"
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Accept-Ranges: bytes
```

Shouldn't we send a charset parameter, or is application/json by definition UTF-8?

**Comment by annevk** [comment]
It's UTF-8 by definition.

**Comment by foolip** [comment]
OK, so it's a Chromium bug. https://crbug.com/438464
