### ISSUE TITLE
Allow username renames on the wiki

### ISSUE THREAD

**Issue by domenic** [whatwg/misc-server#151]
@hober mentioned that her username is incorrect and she'd like to rename. However this appears not to be possible without installing a plugin: https://superuser.com/q/1394701/22738

It'd be nice if we could fix this sooner rather than later for @hober specifically. But in general, when we do the server migration for wiki to DigitalOcean apps, let's make sure we can get plugins like that one installed as part of the build process.

**Comment by foolip** [comment]
We could probably also do renames as part of the migration by doing search/replace in the database export.

**Comment by GPHemsley** [comment]
Didn't realize there was a ticket for this. I have enabled the extension, which comes included with MediaWiki by default.

Administrators can now rename users, though an administrator cannot rename themselves.

> We could probably also do renames as part of the migration by doing search/replace in the database export.

I would strongly recommend against any such adhoc solution for this problem or any other. MediaWiki and its community is fairly robust. It is unlikely that we would need to roll our own anything.

**Comment by annevk** [comment]
It should be all good now.

**Comment by hober** [comment]
Thank you!
