### ISSUE TITLE
wiki history doesn't work

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#27]
https://wiki.whatwg.org/index.php?title=Main_Page&action=history

@gphemsley, can you take a look? Noticed by @Hixie.

**Comment by GPHemsley** [comment]
That's the second time now... I think it has something to do with the database not starting on server startup, but I haven't figured out _why_ that isn't happening.

**Comment by GPHemsley** [comment]
@foolip Can you try to follow this and see if I missed something?

https://mariadb.com/kb/en/library/starting-and-stopping-mariadb-automatically/

**Comment by GPHemsley** [comment]
Oh, wait... my screen sessions still exist, so that means the server was not restarted. Which means something else is killing the database.

**Comment by foolip** [comment]
Maybe the machine just has too little memory for the job? Can you see how much memory is being used?

**Comment by GPHemsley** [comment]
```top - 05:05:11 up 69 days, 22:33,  1 user,  load average: 0.05, 0.04, 0.00
Tasks: 101 total,   3 running,  98 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.0 us,  0.7 sy,  0.0 ni, 96.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.7 st
KiB Mem :   504404 total,    10308 free,   290456 used,   203640 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   166512 avail Mem 
```

**Comment by GPHemsley** [comment]
Hmm... it looks like mysqld is consistently using 22% of memory.

**Comment by foolip** [comment]
So it's working now. The metrics graphs on DigitalOcean are broken now, so can you somehow log what the memory usage is over time to see if it's because of memory next time this happens?

**Comment by GPHemsley** [comment]
It's working now because I went in and (re)started mysqld, yeah.

As far as logging memory usage over time, I'm not sure I know how to do that reliably.

**Comment by foolip** [comment]
I'll add a test for this to notice when it breaks again.

**Comment by foolip** [comment]
Tests in https://github.com/whatwg/misc-server/pull/37

**Comment by foolip** [comment]
OK, this is currently broken. From the bottom of https://wiki.whatwg.org/index.php?title=Main_Page&action=history:
<img width="727" alt="screen shot 2017-11-11 at 3 56 11 pm" src="https://user-images.githubusercontent.com/498917/32690552-e8a894e0-c6f8-11e7-8c20-0e7c56e1d289.png">

@GPHemsley, is there any way to tell what happened here? Should we just try giving this machine more RAM, or what?

**Comment by foolip** [comment]
Probably fixed by adding more swap space.
