### ISSUE TITLE
Upgrade to MediaWiki 1.27.x

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#31]
We are using MediaWiki 1.23.17.

@gphemsley, can you look into this? When it's upgraded, I'd like to add some monitoring so that we know when a new release has happened and can upgrade fast every time.

**Comment by GPHemsley** [comment]
I've got us on LTS versions, so the upgrade would be to 1.27.x. I'm also on the mediawiki-announce mailing list, so I know when new versions are coming.

The upgrade procedure is a little esoteric for our setup, so I'll have to document it somewhere...

**Comment by GPHemsley** [comment]
Upgrade to 1.27.4 is complete, except possibly for some extension prerequisites. Installation using composer is dying due to the lack of swap space on the server.

**Comment by foolip** [comment]
We're now on MediaWiki 1.31.2, but need to upgrade again. @GPHemsley would you be able to write down the steps you run on the server so that others can also perform upgrades?

**Comment by GPHemsley** [comment]
This ticket should have been closed long ago. We remain on the current LTS branch (1.31), so there is nothing to upgrade to right now. (I've previously made the determination that nothing between 1.31.2 and 1.31.5 is urgent or relevant for the functionality we use.)

**Comment by annevk** [comment]
See https://github.com/whatwg/misc-server/issues/112#issuecomment-562607410 for the remainder.
