### ISSUE TITLE
Optimize whatwg.org redirects

### ISSUE THREAD

**Issue by mathiasbynens** [whatwg/misc-server#4]
E.g. `http://whatwg.org/C` (over HTTP) first redirects to `http://www.whatwg.org/C` (still on HTTP), which then redirects to `https://whatwg.org/C` (HTTPS, finally), which finally redirects to `https://html.spec.whatwg.org/multipage/`.

``` bash
$ curl -sIL 'http://whatwg.org/C#entity-lang' | grep Location
Location: http://www.whatwg.org/C
Location: https://whatwg.org/C
Location: https://html.spec.whatwg.org/multipage/
```

Ideally, there’d be only one redirect.

At the very least, the redirect to `http://` should be avoided.

Related: any chance the `.htaccess` for whatwg.org could be made part of this repository?

**Comment by annevk** [comment]
@Hixie controls that server.

**Comment by annevk** [comment]
@foolip fixed this. We now do a redirect to HTTPS first (as per HSTS preload requirements) and then a redirect to the final location.
