### ISSUE TITLE
Set up swap space for wiki.whatwg.org

### ISSUE THREAD

**Issue by GPHemsley** [whatwg/misc-server#45]
Things are running out of memory and dying (e.g. mysqld) because we have no swap space set up on the wiki.whatwg.org server:

```
gphemsley@multicol:/var/www/wiki.whatwg.org$ free -m
              total        used        free      shared  buff/cache   available
Mem:            492         319           8          53         164         106
Swap:             0           0           0
```

Useful resources:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04
https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

This is ultimately blocking #31.

**Comment by foolip** [comment]
I followed https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04 to give it 4GB of swap. The config for this server isn't tracked by version control anywhere, so that's it.
