### ISSUE TITLE
Per-domain setup

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#5]
Each domain we have needs:

* A Let's Encrypt certificate (for now we'll have a per-domain certificate (maybe also covering www.domain), we might change strategy later once Let's Encrypt has wildcards to have more connection coalescing)
* Any request to HTTP needs to redirect to the same location on HTTPS (so no cross-origin redirects for HTTP) and also include Access-Control-Allow-Origin *.
* Any HTTPS response needs HSTS as per https://github.com/whatwg/misc-server/blob/master/shared/partof.whatwg.org..htaccess even if the domain's sole purpose is to be a redirect

If the domain is a redirect domain:

* Only redirect / (permanently) and include a robots.txt that disallows robots.

If the domain hosts a GitHub repository:

* It'll need the public key from the corresponding GitHub repository. Each repository has its own private key (as an encrypted resource) and a public key (not checked in, so ask whoever maintains that repository)

**Comment by annevk** [comment]
Note that fixing this will fix #4 eventually.

**Comment by annevk** [comment]
DNS for new and relocated domains needs to be 165.227.248.76.

**Comment by annevk** [comment]
Future considerations: 

* DNS CAA record to limit ourselves to Let's Encrypt
* Ensure IPv6 works

**Comment by foolip** [comment]
> Any request to HTTP needs to redirect to the same location on HTTPS

I don't know if there are drawbacks, but https://github.com/whatwg/misc-server/blob/master/debian/apache/http-to-https.conf now simply redirects anything HTTP, even if it doesn't know what the domain is. Even localhost or by IP.

> Any HTTPS response needs HSTS

Yep, that can probably be put into a single place and apply to everything, given that we don't have to use .htaccess for those kinds of things now.

> Only redirect / (permanently) and include a robots.txt that disallows robots

I was thinking perhaps https://github.com/whatwg/misc-server/blob/master/debian/DOMAINS and the code that processes could be a little bit more clever, to perhaps group redirecting aliases into the same certificate as it redirects to. That could possibly also generate a handler for robots.txt.

> Ensure IPv6 works

There is a slight complication here, namely that the DigitalOcean floating IP is IPv4. So if we ever make use of the ability to redirect that IP to another droplet, I think it'll break something about IPv6.

**Comment by domenic** [comment]
> DNS CAA record to limit ourselves to Let's Encrypt

build.whatwg.org is using Amazon certificate stuff, but I could switch eventually.

**Comment by foolip** [comment]
I think this is the only remaining thing:
> If the domain is a redirect domain:
> - Only redirect / (permanently) and include a robots.txt that disallows robots.

@annevk why do we need robots.txt for these? Is there anything else this issue was intended to cover?

**Comment by annevk** [comment]
I don't remember. I'm okay with closing this at this point.
