### ISSUE TITLE
Use pm2 startup for noembed server

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#54]
See discussion at https://github.com/whatwg/misc-server/pull/53#discussion_r156841811 and actually just `pm2 startup` should be good enough, it auto-detects the init system.

Also, I see that `nodeuser` is the name of the user in that article, if that's a common name we can switch to that instead of `noderunner`.

**Comment by foolip** [comment]
@domenic this is done, right?

**Comment by foolip** [comment]
Hmm, maybe not. `pm2` is used, but we use crontab to start it.

**Comment by domenic** [comment]
Right, this is about replacing https://github.com/whatwg/misc-server/blob/afb327ed66c644685c8d14dd457c4e1399813219/debian/noembed/04-participate#L13 with some `pm2 startup` incantation. It's not clear that's really worth the effort, but maybe it'd be nicer in some ways.

**Comment by domenic** [comment]
This is obsolete on our new hosting platform :)
