### ISSUE TITLE
admin@wiki.whatwg.org doesn't work

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#59]
https://wiki.whatwg.org/ says this in a gray box:
> A user account is required in order to edit this wiki, but we've had to disable public user registrations due to spam.
>
> To request an account, ask an autoconfirmed user on IRC (such as one of these permanent autoconfirmed members) or send an e-mail to admin@wiki.whatwg.org with your desired username and an explanation of the first edit you'd like to make. (Do not use this e-mail address for any other inquiries, as they will be ignored or politely declined.)

I suspected that admin@wiki.whatwg.org wouldn't work, which was confirmed by emailing it. @GPHemsley, where does this text come from, and what should the email be instead?

**Comment by annevk** [comment]
Maybe we should just restrict it to IRC for now. Even when the email address still worked it's been a long time since I got an email.

**Comment by foolip** [comment]
That sounds good. @GPHemsley, do you know where to edit this text?

**Comment by annevk** [comment]
I updated https://wiki.whatwg.org/wiki/MediaWiki:Anonnotice.

**Comment by foolip** [comment]
Thanks!

**Comment by GPHemsley** [comment]
That e-mail address actually gets quite a bit of e-mail, though admittedly most of it is spam.

I do find a handful of unanswered legitimate e-mails every time I go through it, but yeah, IRC is probably the better way to go. Last e-mail I have dates to September 6.
