### ISSUE TITLE
idea.whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#6]
I was initially thinking that we should have the same setup as we do with spec.whatwg.org, but I don't think we need to as we don't want to redirect whatwg.org/ideas/. That URL should simply never exist.

So what would be the best way to host content at / on idea.whatwg.org? Host that here in a subdirectory for now?

**Comment by annevk** [comment]
By the way, I don't think Ideas needs to be a top-level tab on whatwg.org. I think we should introduce it on spec.whatwg.org as something like "We also host a number of [ideas]".

**Comment by foolip** [comment]
How about we just start with links to the ideas that exist? There's no process to document, after all.

**Comment by annevk** [comment]
I didn't mean to suggest otherwise. All I wanted to know is where to put that document.

**Comment by annevk** [comment]
Here is the document I think we should put on idea.whatwg.org (see also https://github.com/whatwg/whatwg.org/pull/40 for the corresponding change to spec.whatwg.org):
```
<!DOCTYPE HTML>
<!-- Note: this resource is served from https://idea.whatwg.org/ -->
<html lang="en">
 <head>
  <title>Web Hypertext Application Technology Working Group Ideas</title>
  <link rel="stylesheet" href="https://whatwg.org/style/tabbed-pages">
  <link rel="icon" href="https://resources.whatwg.org/logo.svg">
 </head>
 <body>
  <h1>
   <span class="the">The</span>
   <strong class="what">Web Hypertext Application Technology</strong>
   <span class="wg">Working Group</span>
  </h1>
  <ul class="navigation">
   <li><a href="https://whatwg.org/" rel="home">Home</a></li>
   <li><a href="https://spec.whatwg.org">Standards</a></li>
   <li><a href="https://whatwg.org/working-mode">Working Mode</a></li>
   <li><a href="https://whatwg.org/code-of-conduct">Code of Conduct</a></li>
   <li><a href="https://whatwg.org/faq">FAQ</a></li>
  </ul>

  <h2>Ideas</h2>

  <p>The WHATWG works on a number of ideas that aspire to become web platform standards. They are 
  organised somewhat arbitrarily based on the preferences of those editing the ideas.</p>

  <dl>
   <dt><a href="https://books.idea.whatwg.org/">Books</a></dt>
   <dd>
    <p>The Books Standard defines CSS features for book publishing and high-quality printing of web
    pages.</p>
   </dd>

   <dt><a href="https://figures.idea.whatwg.org/">Figures</a></dt>
   <dd>
    <p>The Figures Standard defines CSS features for floating elements around pages and columns.</p>
   </dd>
  </dl>
 </body>
</html>
```

**Comment by foolip** [comment]
That's now live at https://idea.whatwg.org/ but not in version control. Other than "The Books Standard", anything that needs changing?

**Comment by domenic** [comment]
I think "They are organised somewhat arbitrarily based on the preferences of those editing the ideas" isn't very necessary here.

And yeah, "Books Standard" and "Figures Standard" need to change to... something.

I think a new top-level directory in https://github.com/whatwg/whatwg.org/ makes sense. Let me know if you need help setting up the deploy script.

**Comment by domenic** [comment]
Maybe also we'd want to link to https://whatwg.org/working-mode#new-proposals, e.g. "per our working mode"

**Comment by annevk** [comment]
I suggest "The Books specification".

A new top-level directory in whatwg/whatwg.org is an interesting idea. Just call it idea.whatwg.org?

**Comment by domenic** [comment]
Yeah, either that or call it "idea" and rename "src" to something weird like "(root)". But probably your version is better.
