### ISSUE TITLE
Need to add CORS headers everywhere

### ISSUE THREAD

**Issue by domenic** [whatwg/misc-server#68]
Everything we host except things on participate.whatwg.org should be pubicly readable.

This is preventing the new service workers from caching things.

I think this regressed with the switch to nginx.

**Comment by annevk** [comment]
You should be able to cache opaque resources, but they should indeed be using CORS (*, no credentials).

**Comment by domenic** [comment]
Yeah, I figured better to fix our server than to work around it in the service worker.

**Comment by annevk** [comment]
To clarify, all resources from whatwg/whatwg.org need to carry `Access-Control-Allow-Origin: *`.

**Comment by foolip** [comment]
OK, let's do it for all of marquee, which is just static resources, everything else is non-static in some way.

**Comment by foolip** [comment]
And yes, I did break this in https://github.com/whatwg/whatwg.org/commit/928a87b46ed790c5ea86e2ea52056f413f0a0cd6, and I'm pretty sure it was because there were a bunch of configs in directories that were just about caching, and I looked over fonts/ too quickly without spotting the difference.

**Comment by annevk** [comment]
Well, it's not just fonts/. We had this at a higher level too as I indicated in https://github.com/whatwg/misc-server/issues/5. I guess we forgot to double check that requirement early on.
