### ISSUE TITLE
Transition whatwg.org to new hosting

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#7]
To improve our uptime and allow for more admins, we are moving the hosting of whatwg.org from DreamHost to DigitalOcean. These are the domains:
- [x] [blog.whatwg.org](https://blog.whatwg.org)
- [x] [books.idea.whatwg.org](https://books.idea.whatwg.org)
- [x] [books.spec.whatwg.org](https://books.spec.whatwg.org) (redirect)
- [x] <s>[build.whatwg.org](https://build.whatwg.org)</s> (will be left alone in this issue)
- [x] [c.whatwg.org](https://c.whatwg.org) (redirect)
- [x] [compat.spec.whatwg.org](https://compat.spec.whatwg.org)
- [x] [console.spec.whatwg.org](https://console.spec.whatwg.org)
- [x] [developer.whatwg.org](https://developer.whatwg.org) (redirect)
- [x] [developers.whatwg.org](https://developers.whatwg.org) (redirect)
- [x] [dom.spec.whatwg.org](https://dom.spec.whatwg.org)
- [x] [domparsing.spec.whatwg.org](https://domparsing.spec.whatwg.org) (redirect)
- [x] [encoding.spec.whatwg.org](https://encoding.spec.whatwg.org)
- [x] [fetch.spec.whatwg.org](https://fetch.spec.whatwg.org)
- [x] [figures.idea.whatwg.org](https://figures.idea.whatwg.org)
- [x] [figures.spec.whatwg.org](https://figures.spec.whatwg.org) (redirect)
- [x] [forums.whatwg.org](https://forums.whatwg.org)
- [x] [fullscreen.spec.whatwg.org](https://fullscreen.spec.whatwg.org)
- [x] [help.whatwg.org](https://help.whatwg.org) (redirect)
- [x] [html-differences.whatwg.org](https://html-differences.whatwg.org)
- [x] [html.spec.whatwg.org](https://html.spec.whatwg.org)
- [x] [idea.whatwg.org](https://idea.whatwg.org)
- [x] [images.whatwg.org](https://images.whatwg.org)
- [x] [infra.spec.whatwg.org](https://infra.spec.whatwg.org)
- [ ] [lists.whatwg.org](https://lists.whatwg.org)
- [x] [javascript.spec.whatwg.org](https://javascript.spec.whatwg.org) (redirect)
- [x] [mediasession.spec.whatwg.org](https://mediasession.spec.whatwg.org) (redirect)
- [x] [mimesniff.spec.whatwg.org](https://mimesniff.spec.whatwg.org)
- [x] [n.whatwg.org](https://n.whatwg.org)
- [x] [notifications.spec.whatwg.org](https://notifications.spec.whatwg.org)
- [x] [quirks.spec.whatwg.org](https://quirks.spec.whatwg.org)
- [x] [resources.whatwg.org](https://resources.whatwg.org)
- [x] [spec.whatwg.org](https://spec.whatwg.org)
- [x] [specs.whatwg.org](https://specs.whatwg.org) (redirect)
- [x] [storage.spec.whatwg.org](https://storage.spec.whatwg.org)
- [x] [streams.spec.whatwg.org](https://streams.spec.whatwg.org) (check content-type of https://streams.spec.whatwg.org/demos/resources/web-animations.min.js.map)
- [x] [svn.whatwg.org](https://svn.whatwg.org)
- [x] [url.spec.whatwg.org](https://url.spec.whatwg.org) (needs audit of extension-less files)
- [x] [validator.whatwg.org](https://validator.whatwg.org) (redirect)
- [x] [webvtt.spec.whatwg.org](https://webvtt.spec.whatwg.org) (redirect)
- [x] [whatwg.org](https://whatwg.org) and [www.whatwg.org](https://www.whatwg.org) (needs audit of extension-less files)
- [x] [wiki.whatwg.org](https://wiki.whatwg.org) (but: https://github.com/whatwg/misc-server/issues/27)
- [x] [xhr.spec.whatwg.org](https://xhr.spec.whatwg.org)
- [x] [xn--7ca.whatwg.org](https://xn--7ca.whatwg.org) (redirect)

**Comment by foolip** [comment]
Separate from the hosting question, these are static sites that could be hosted inside https://github.com/whatwg/whatwg.org/:
- help.whatwg.org
- images.whatwg.org
- n.whatwg.org
- resources.whatwg.org (already in https://github.com/whatwg/resources.whatwg.org, leave alone?)

@annevk?

**Comment by annevk** [comment]
As a next step I think we should try to move everything that's not *.spec.whatwg (so we will move spec.whatwg), blog.whatwg, or wiki.whatwg. Then we could move blog.whatwg and wiki.whatwg and maybe html.whatwg (it seems like we'll continue to have a need to execute scripts so we might want to make a longer term plan first), and last all the specs (that are all intertwined I think).

**Comment by foolip** [comment]
Yeah, let's leave resources.whatwg.org alone, because it's used by HTML it might get more traffic, so might not want it deployed in the same place. Will you put images.whatwg.org and n.whatwg.org into the repo though? We can set up the deploy for that before DNS is changed.

**Comment by foolip** [comment]
Oops, that's https://github.com/whatwg/whatwg.org/pull/52

**Comment by sideshowbarker** [comment]
help.whatwg.org can just be redirected

**Comment by foolip** [comment]
resources.whatwg.org is a tricky one, because it's used by all specs. If it's not on the same IP and using the same cert as the specs, then load time will be less awesome than it could be. Maybe we should try hosting everything static on a single machine, and just make it beefier?

**Comment by annevk** [comment]
I think we should host all static things on the same server instance. But note that any performance benefits won't come until Let's Encrypt actually offers multi-domain wildcard certificates.

**Comment by foolip** [comment]
We could also request a single cert for all the domains on a single machine.

**Comment by foolip** [comment]
The downside is that if the DNS of any one of those domains changes, I think certbot renew would start failing.

**Comment by foolip** [comment]
The current setup for spec.whatwg.org (nested inside whatwg.org source-wise) leads to fun:
https://whatwg.org/specs/web-forms/current-work/
https://spec.whatwg.org/web-forms/current-work/

These both work, but the latter looks like an accident. I suggest that we just let those URLs go 404, and preserve only the original URLs.

**Comment by annevk** [comment]
Yes, we should do that.

**Comment by foolip** [comment]
I'm extracting out spec.whatwg.org now.

**Comment by foolip** [comment]
Handing html-differences in https://github.com/whatwg/html-differences/pull/5

**Comment by foolip** [comment]
I've added lists.whatwg.org to the list, it's currently broken by HSTS, and it would be nice to restore it somehow.

**Comment by annevk** [comment]
@foolip I suspect we can't get ownership of that until we have DNS control since it's highly likely a name that's tightly coupled to DreamHost's managed mailing list service. (When we take that over we should make sure that whatwg@lists.whatwg.org still works. Same for whatwg@whatwg.org.)

**Comment by foolip** [comment]
Right, so the challenge is how to get the archives from DreamHost and, presumably, to keep updating them if we're not shutting down all of the lists.

**Comment by annevk** [comment]
Well, the main list we'd end up keeping is also archived at https://lists.w3.org/Archives/Public/public-whatwg-archive/. If we can it might be better to just find a mapping from the old URL to those URLs and redirect everything there. The alternative would be to install the same mailing list software (unless we want to deal with local redirects).

**Comment by foolip** [comment]
That would work, if https://lists.w3.org/Archives/Public/public-whatwg-archive/ contains everything that our own archives do. Still probably a lot of work.

**Comment by annevk** [comment]
It should be complete, but yes.

**Comment by foolip** [comment]
@domenic, is any action needed for build.whatwg.org? At the very least we shouldn't mess up its DNS in eventual DNS handover.

**Comment by domenic** [comment]
It might be a good idea for me to move that all from my personal AWS to one of the droplets. It'd also be good to switch to LetsEncrypt.

If you're up for it, I'd appreciate the help doing so; the readme at https://github.com/domenic/wattsi-server should have most of the info. Then you could switch the DNS to point to the droplet and I could shut down my server completely.

Eventually we probably want to move that to a whatwg/build.whatwg.org repository.

**Comment by foolip** [comment]
I've added it to the list so that it's not forgotten.

**Comment by foolip** [comment]
What's left blocking HTML is now print.pdf. Should try to make https://github.com/izh1979/makepdf part of the Travis build. Thanks @izh1979 for putting it together!

**Comment by foolip** [comment]
So I'm thinking maybe we could just build/install https://github.com/izh1979/makepdf on Travis for each commit?

**Comment by foolip** [comment]
The other alternative would be to make it part of build.whatwg.org, but then we'd have to worry about malicious input, and not just processing what gets merged into the spec.

**Comment by annevk** [comment]
The more we can outsource to Travis the better I think.

**Comment by foolip** [comment]
Yeah, otherwise we'll have to either run PHP on the machine serving HTML, or on some other machine that accepts the PDF and deploys it.

Getting the pdfbuild repo working on Travis isn't trivial, but is probably possible in the end.

**Comment by izh1979** [comment]
Or you can rewrite the script in some other language. ;-) It's not big, nor complex.
And it's easier when you have working variant. ;-)

**Comment by snuggs** [comment]
@izh1979 @foolip where would said script be located? Thanks in advance!

**Comment by annevk** [comment]
@snuggs the script used for the HTML Standard is hosted at https://github.com/izh1979/makepdf and that .php page runs it.

**Comment by foolip** [comment]
Well, this is amusing, while trying to figure out how to do this, I came across https://www.princexml.com/forum/topic/2666/using-better-compression-and-pdf-size-optimization which is @izh1979 asking about compressing PDFs :)

**Comment by izh1979** [comment]
Yeah, I've generating PDFs for WHATWG HTML spec for about of 3 years. ;-)

**Comment by foolip** [comment]
All that remains here now is lists.whatwg.org, which is tied together with the DNS. Somebody needs to learn how email actually works to do this job, maybe we should liaison with the IETF :)

**Comment by foolip** [comment]
An update on lists.whatwg.org. https://packages.debian.org/sid/mailman3-suite looked very promising, but is only in Debian unstable, and installation didn't actually work out of the box on a fresh Debian unstable, neither an (upgraded) DigitalOcean droplet or in a debian:unstable Docker image. (I think it failed to create/start a postgres db, and is probably easy-ish to fix.)

Because Debian unstable also doesn't get security updates in the same way, it's probably best to follow http://docs.mailman3.org/en/latest/prodsetup.html or similar, and https://github.com/whatwg/misc-server/commit/213da82f2ddc0d97d7fff5987d56947ea97e0b7a is what I tried so far. With some more tinkering it's probably possible to make that work.

I haven't tried https://github.com/maxking/docker-mailman yet because it seems somewhat implausible to me that the total complexity will be lower, one still has to have a database and web server separately, and we don't want archives, so it'd pretty much just give us mailman3-core and the django stuff.

On setting up an email server (not just mailman), something very discouraging at https://www.digitalocean.com/community/tutorials/how-to-set-up-a-postfix-e-mail-server-with-dovecot:
> Postfix has several hundred configuration parameters. If you want to administer a mail server that reliably delivers business requirements to a sizable organization, you should make yourself intimate with all of them (man 5 postconf). This tutorial will *not* be enough, on its own, to make you a competent professional email admin.

**Comment by domenic** [comment]
Oh, wow, thanks for looking into this further. Can you explain a bit more about the docker-mailman not working? It seems to have the database inside the container.

**Comment by foolip** [comment]
I haven't tried setting it up the Docker image. From my reading of https://hub.docker.com/r/alexbarcelo/mailman3/ last time, given the `POSTGRES_HOST` configuration I surmised that the database would be external, but maybe it'll use an internal one if not.

**Comment by foolip** [comment]
Filed https://github.com/whatwg/misc-server/issues/75 for what remains.

**Comment by domenic** [comment]
Also filed https://github.com/whatwg/misc-server/issues/77
