### ISSUE TITLE
Transition mail server and lists.whatwg.org to new hosting

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#75]
This is all that remains of https://github.com/whatwg/misc-server/issues/7.

Search the issue for "mail" for some previous attempts/discussion.

**Comment by foolip** [comment]
https://www.c0ffee.net/blog/mail-server-guide and https://news.ycombinator.com/item?id=16238937 might be useful here.

**Comment by foolip** [comment]
This issue came up in https://github.com/whatwg/misc-server/issues/107 and I have a proposal for how to proceed. Running a mail server and mailman ourselves is so much hassle that none of us have been willing to tackle it, but if we only had to maintain simple forward email aliases things would be much simpler.

https://lists.w3.org/Archives/Public/public-whatwg-archive/ is the W3C-hosted archive of the list, so what I suggest is that we ask to use the W3C's list management system for membership too. I think there are two options:
- Create public-whatwg@w3.org and make that the canonical address
- Keep whatwg@whatwg.org as the canonical address by forwarding to a W3C list, which is configured to treat whatwg@whatwg.org as the list address.

@sideshowbarker I think the first option would be fine, but can you check if the second is possible?

Finally, for actually forwarding email, we'd configure the MX records to point to something that WHATWG admins have shared access to, and DigitalOcean does not provide that. Rather, we will need to use an email provider with custom domains using MX records. I've done this for foolip.org for ages, and also just confirmed that fastmail.com is easy to set up with way using foolip.com.

@Hixie I'll email you with a few more questions.

**Comment by sideshowbarker** [comment]
> https://lists.w3.org/Archives/Public/public-whatwg-archive/ is the W3C-hosted archive of the list, so what I suggest is that we ask to use the W3C's list management system for membership too. I think there are two options:
> 
> * Create [public-whatwg@w3.org](mailto:public-whatwg@w3.org) and make that the canonical address
> * Keep [whatwg@whatwg.org](mailto:whatwg@whatwg.org) as the canonical address by forwarding to a W3C list, which is configured to treat [whatwg@whatwg.org](mailto:whatwg@whatwg.org) as the list address.
> 
> @sideshowbarker I think the first option would be fine, but can you check if the second is possible?

cc @gosko (who manages the W3C mail systems) so he can comment here directly

**Comment by gosko** [comment]
> https://lists.w3.org/Archives/Public/public-whatwg-archive/ is the W3C-hosted archive of the list, so what I suggest is that we ask to use the W3C's list management system for membership too. I think there are two options:
> 
>     * Create [public-whatwg@w3.org](mailto:public-whatwg@w3.org) and make that the canonical address
> 
>     * Keep [whatwg@whatwg.org](mailto:whatwg@whatwg.org) as the canonical address by forwarding to a W3C list, which is configured to treat [whatwg@whatwg.org](mailto:whatwg@whatwg.org) as the list address.
> 
> 
> @sideshowbarker I think the first option would be fine, but can you check if the second is possible?

Hosting the list seems doable, but if W3C were to host it I would prefer to change the canonical address and not pretend it's still whatwg@whatwg.org, though that could be an alias.

I was going to suggest renaming public-whatwg-archive to public-whatwg and redirecting the archives but unfortunately public-whatwg is already taken: https://lists.w3.org/Archives/Public/public-whatwg/

Note that moving the list to W3C would mean the email headers would change, in particular the List-Id: would be different and the subject tagging would no longer be available.

**Comment by foolip** [comment]
@gosko, changing the canonical address would be fine, but if sending to whatwg@whatwg.org could still work that would be good. Perhaps just setting it up to forward to the w3.org address would allow that to work?

The WHATWG Community Group is closed, so would it be possible to use public-whatwg@w3.org while keeping the existing archives of that?

I think we'll just have to accept that people will need to update their email filters, but I don't think the volume of email will be high, so that's OK.

**Comment by foolip** [comment]
@gosko there is a problem with any plan to transfer that I didn't think of at the outset, and that's that those who signed up to lists.whatwg.org didn't agree to such a transfer of their contact info. Trying to sort that out is probably more effort than it's worth, so which I'd still appreciate understanding the options here, I wouldn't spend *too* much time on this given this uncertainty.

**Comment by gosko** [comment]
> The WHATWG Community Group is closed, so would it be possible to use [public-whatwg@w3.org](mailto:public-whatwg@w3.org) while keeping the existing archives of that?

@foolip This is possible, but seems suboptimal to me because the archives of whatwg@whatwg.org would be split between two areas, and the public-whatwg archives would have a confusing mix of the CG list and whatwg@whatwg.org.

**Comment by foolip** [comment]
Thanks @gosko for investigating!

Since the volume on these lists is so low and the effort to keep them working indefinitely non-trivial, the new plan I'd like to propose is:
- Make the list addresses auto-reply with a message saying they're no longer active and pointing out how to communicate instead.
- Redirect lists.whatwg.org to https://web.archive.org/web/20140401085610/http://lists.whatwg.org/pipermail/whatwg-whatwg.org/ and/or the W3C archives as best we can, maybe depending on the requested URL.

**Comment by foolip** [comment]
The list addresses auto-reply as suggested above.

I've revised the plan for lists.whatwg.org a little bit, however:
- host a static copy of the parts of the archives that can be easily restored from a scrape I did and web.archive.org.
- if any known holes still remain, add a 404 handler explaining how one could dig deeper to find the original email

**Comment by annevk** [comment]
I like that idea. I might even encourage folks to file an issue on whatwg/meta if they encounter such a broken link so we can help them out.

**Comment by domenic** [comment]
This is done :)
