### ISSUE TITLE
Transition build.whatwg.org to new hosting

### ISSUE THREAD

**Issue by domenic** [whatwg/misc-server#77]
Currently it's on my personal AWS and it's run out of https://github.com/domenic/wattsi-server. I should transfer the repository to whatwg/build.whatwg.org and so on.

**Comment by annevk** [comment]
Can we do it all on Travis instead?

**Comment by annevk** [comment]
Hmm, I guess we still want to support local builds without having to install anything locally.

**Comment by domenic** [comment]
This is done: https://github.com/whatwg/misc-server/tree/master/debian/isindex
