### ISSUE TITLE
Write tests for redirects and SSL certs

### ISSUE THREAD

**Issue by foolip** [whatwg/misc-server#9]
In https://github.com/whatwg/misc-server/issues/7 and https://github.com/whatwg/misc-server/pull/8 we're changing a lot of things. It would be nice to a (python?) script that checks for various URLs that they're correctly redirected, and perhaps also that the certs are valid. This could run as a daily Travis job to help catch errors.

@sideshowbarker

**Comment by annevk** [comment]
Could maybe even write in bash given https://github.com/whatwg/misc-server/issues/4#issue-127230752. Dump the expected output in a file and then compare the output on a given day to that file. I'm not sure how you'd compare files though.

**Comment by foolip** [comment]
https://serverlesscode.com/post/ssl-expiration-alerts-with-lambda/ looks promising.

(I've had a problem where I've renewed certs and thus gotten no warning from letsencrypt, but not reloaded the web server.)

**Comment by foolip** [comment]
This was done in https://github.com/whatwg/misc-server/pull/18 and https://github.com/whatwg/misc-server/pull/19, with some tweaking going on in https://github.com/whatwg/misc-server/pull/25.
