### ISSUE TITLE
Transfer ownership of S3 instance backing whatpr.org

### ISSUE THREAD

**Issue by annevk** [whatwg/misc-server#98]
@foolip @sideshowbarker I think you'd be ideal for handling this given you handle most of the existing server infrastructure. Let me know if that'd be prohibitive.

cc @tobie

**Comment by foolip** [comment]
@tobie what would the concrete work here be? Are different S3 buckets used for WHATWG and everything else, or is it just that the custom domain (whatpr.org) makes the URLs nicer for WHATWG preview?

How abstracted away is the storage backend, could it be replaced with something on DigitalOcean easily to keep all our hosting in one place?

**Comment by tobie** [comment]
It's a dedicated S3 instance. With some other AWS services to handle the domain name (notably Route 53, iirc).

I'm about to setup an Open Collective account to get funding to continue supporting PR Preview and Specref. If that gets funded, I'm happy to continue maintaining that part of the infrastructure and continue to improve the project (e.g. adding support for mono repos like the CSSWG's).

**Comment by foolip** [comment]
@tobie did you get Open Collective set up, and is the plan to keep supporting PR Preview?

**Comment by tobie** [comment]
[I have](https://opencollective.com/specinfra), though I haven't promoted it.

**Comment by foolip** [comment]
@tobie could you create a group or whatever the best organization unit is on AWS and add philip@foolip.org so I can see the setup? I'm evaluating what it'd look like to fix https://github.com/whatwg/misc-server/issues/107 using AWS and the setup you describe in https://github.com/whatwg/misc-server/issues/89#issuecomment-475946760 is similar to what I'm attempting.

**Comment by tobie** [comment]
Haha. I'm not touching AWS permissions with a 10-foot pole unless I have three free days behind it to fix whatever I break doing so. I can walk you through it over a call if you want me to, however.

**Comment by foolip** [comment]
Oh my, sounds like you've had some things blow up in the past :)

Let's not to this until there's a practical reason beyond my curiosity, then.

**Comment by domenic** [comment]
I think this is done?

**Comment by tobie** [comment]
Yes. iirc.
